FROM php:5.6-fpm

MAINTAINER hermannsw <symsapiens@gmail.com>

ADD ./laravel.ini /usr/local/etc/php/conf.d
ADD ./laravel.pool.conf /usr/local/etc/php-fpm.d/

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libmemcached-dev \
    curl \
    libpng12-dev \
    libfreetype6-dev \
    libjpeg62-turbo \
    libssl-dev \
    libmcrypt-dev \
    libjpeg-dev \
    libpng12-0 \
    libxpm-dev \
    zlib1g-dev \
    --no-install-recommends \
    && rm -r /var/lib/apt/lists/*

# install mcrypt library
RUN docker-php-ext-install mcrypt

# configure gd library
RUN docker-php-ext-configure gd \
    --enable-gd-native-ttf \
    --with-jpeg-dir=/usr/lib/x86_64-linux-gnu \
    --with-png-dir=/usr/lib/x86_64-linux-gnu \
    --with-freetype-dir=/usr/include/freetype2 \
    --with-xpm-dir=/usr/lib/x86_64-linux-gnu

RUN docker-php-ext-install gd

# Install extensions using the helper script provided by the base image
RUN docker-php-ext-install \
    pdo_pgsql

RUN docker-php-ext-install \
    mbstring \
    gettext \
    opcache

RUN usermod -u 1000 www-data

WORKDIR /var/www/laravel

CMD ["php-fpm"]

EXPOSE 9000
