FROM laradock/php-fpm:2.2-7.2

MAINTAINER hermannsw <symsapiens@gmail.com>

ADD ./laravel.ini /usr/local/etc/php/conf.d
ADD ./laravel.pool.conf /usr/local/etc/php-fpm.d/

RUN apt-get update && apt-get install -y \
    curl \
    libfreetype6-dev \
    libmcrypt-dev \
    libmemcached-dev \
    libpq-dev \
    libssl-dev \
    libxpm-dev \
    zlib1g-dev \
    --no-install-recommends \
    && rm -r /var/lib/apt/lists/*

RUN usermod -u 1000 www-data

WORKDIR /var/www/laravel

CMD ["php-fpm"]

EXPOSE 9000
